08_django/proiect/aplicatie1/urls.py
from django.urls import path

from aplicatie1 import views

app_name = 'aplicatie1'

urlpatterns = [
    path('', views.LocationView.as_view(), name='lista_locatii'),
    path('adaugare/', views.CreateLocationView.as_view(), name='adaugare'),
    path('<int:pk>/modificare/', views.UpdateLocationView.as_view(), name='modificare'),
    path('<int:pk>/dezactiveaza/', views.deactivate_location, name='dezactiveaza'),
    path('<int:pk>/activeaza/', views.activate_location, name='activeaza'),
]

08_django/proiect/aplicatie1/forms.py
from django import forms
from django.forms import TextInput

from aplicatie1.models import Location


class LocationForm(forms.ModelForm):
    class Meta:
        model = Location
        fields = ['city', 'country']
        widgets = {
            'city': TextInput(attrs={'placeholder': 'City value', 'class': 'form-control'}),
            'country': TextInput(attrs={'placeholder': 'Country value', 'class': 'form-control'}),
        }

    def __init__(self, pk, *args, **kwargs):
        super(LocationForm, self).__init__(*args, **kwargs)
        self.pk = pk

    def clean(self):
        city_value = self.cleaned_data.get('city')
        country_value = self.cleaned_data.get('country')
        if self.pk:
            if Location.objects.filter(city__icontains=city_value, country__icontains=country_value).exclude(id=self.pk).exists():
                self._errors['city'] = self.error_class(['Orasul si tara deja exista'])
            else:
                if Location.objects.filter(city__icontains=city_value, country__icontains=country_value).exclude(id=self.pk).exists():
                    self._errors['city'] = self.error_class(['Orasul si tara deja exista'])

08_django/proiect/templates/aplicatie1/location_form.html
{% extends 'base.html' %}
{% block content %}
    <div class = "col-md-12">
        <form method="POST">
            {% csrf_token %}
            {% for field in form %}
            <div class="col-md-6"> {{field.label }} {{field}} {{field.errors}} </div> <br>

            {% endfor %}
            <button type = "submit" class = "btn btn-success">Salveaza</button>
        </form>
    </div>
{% endblock %}

08_django/proiect/templates/aplicatie1/location_index.html
{% extends 'base.html' %}
{% block content %}
    <a class = "btn btn-primary" href="{% url 'aplicatie1:adaugare' %}">Adaugare locatii</a>
    <table class ="table">
        <thead>
            <tr>
                <th> Index </th>
                <th> City</th>
                <th> Country </th>
                <th> State </th>
                <th> Actions </th>
            </tr>
        </thead>

        <tbody>
            {% for item in location_list %}
                <tr>
                    <td>{{forloop.counter}}</td>
                    <td>{{item.city}}</td>
                    <td>{{item.country}}</td>
                    <td>
                        {% if item.active == 0 %}
                            Inactiv
                        {% else %}
                            Activ
                        {% endif %}
                    </td>
                    <td>
                        <a class ="btn btn-success" href = "{% url 'aplicatie1:modificare' item.id %}">Editare </a>
                        {% if item.active == 0 %}
                            <a class = "btn btn-danger" href="{% url 'aplicatie1:activeaza' item.id %}">Activeaza</a>
                        {% else %}
                            <a class = "btn btn-danger" href="{% url 'aplicatie1:dezactiveaza' item.id %}"> Dezactiveaza </a>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

08_django/proiect/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Proiect django</title>
    <link rel = "stylesheet" href = "https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" type = "text/css">

</head>
<body>
    <div class ="container"/>
    <div class = "row">
        <div class = "col-md-12">
            <nav>
                <a class = "btn" href = "/admin/">Admin</a>
                 {% if request.user.is_authenticated %}
                <a class = "btn" href = "{% url 'aplicatie1:lista_locatii' %}">Locatii</a>
                <form method="post" action="{% url 'logout' %}">
                    {% csrf_token %}
                    <button class="btn" type="submit">logout</button>
                </form>
                {% endif %}
            </nav>
        </div>
    </div>
    </div>
    {% block content %}
    {% endblock %}
</body>
</html>